Revert "AsyncProcess: improve, fix & test fd close loop" (#226)
Reverting swiftlang/swift-sdk-generator#223 due to failure on Amazon Linux 2: https://ci.swift.org/job/swift-PR-toolchain-amazonlinux2/82/console

```
05:24:57  In file included from /home/build-user/swift-sdk-generator/Sources/CProcessSpawnSync/spawner.c:31:
05:24:57  /home/build-user/swift-sdk-generator/Sources/CProcessSpawnSync/internal-helpers.h:69:26: error: call to undeclared function 'getdents64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
05:24:57      while ((bytes_read = getdents64(dir_fd, (struct dirent64 *)buffer, sizeof(buffer))) > 0) {
05:24:57                           ^
05:24:57  1 error generated.
```